name: SoapsQuest
version: '1.0.0-SNAPSHOT'
main: com.soaps.quest.SoapsQuest
api-version: '1.20'
author: AlternativeSoap
description: Minecraft quest system using paper items
website: www.soapsuniverse.com
softdepend: [Vault, PlaceholderAPI]

commands:
  soapsquest:
    description: Main quest command
    usage: /soapsquest <give|list|generate|reload|progress|addreward|removereward>
    aliases: [sq]
    permission: soapsquest.use

permissions:
  soapsquest.*:
    description: Gives access to all SoapsQuest permissions
    default: op
    children:
      soapsquest.use: true
      soapsquest.give: true
      soapsquest.list: true
      soapsquest.list.click: true
      soapsquest.generate: true
      soapsquest.reload: true
      soapsquest.progress: true
      soapsquest.progress.others: true
      soapsquest.addreward: true
      soapsquest.removereward: true
  
  soapsquest.use:
    description: Basic permission to use quest commands
    default: true
  
  soapsquest.give:
    description: Permission to give quest papers to players
    default: op
  
  soapsquest.list:
    description: Permission to list all available quests
    default: true
  
  soapsquest.list.click:
    description: Permission to click and claim quests from /sq list
    default: true
  
  soapsquest.generate:
    description: Permission to generate random quests
    default: op
  
  soapsquest.reload:
    description: Permission to reload plugin configuration
    default: op
  
  soapsquest.progress:
    description: Permission to check own quest progress
    default: true
  
  soapsquest.progress.others:
    description: Permission to check other players' quest progress
    default: op
  
  soapsquest.addreward:
    description: Permission to add rewards to quests
    default: op
  
  soapsquest.removereward:
    description: Permission to remove rewards from quests
    default: op